### ISSUE TITLE
Unable to install with Swift Package Manager

### ISSUE THREAD

**Issue by cristian-azov** [amadeus4dev/amadeus-ios#4]
Running `swift build` results in the following error:

```
Fetching https://github.com/amadeus4dev/amadeus-swift.git
error: the package dependency graph could not be resolved; unable to find any available tag for the following requirements:
    https://github.com/amadeus4dev/amadeus-swift.git @ 1.0.0..<2.0.0
```

By the time of this writing there were no git tags indeed.

**Comment by alnacle** [comment]
Hi Cristian, sorry for my late response!

The SDK is not fully stable and that's why we didn't release (tag) any 1.0.0 version yet. In the meantime, if you want to test the SDK, try to use 'master' branch as dependency on your Package.swift:

```
.package(
    url: "https://github.com/amadeus4dev/amadeus-swift",
    .branch("master")
)
```
We hope to release a stable version very soon. Stay tuned!
